FROM --platform=$TARGETPLATFORM golang:1.18
#ENV GOPROXY https://goproxy.cn,direct


# Install git, process tools, lsb-release (common in install instructions for CLIs)
RUN apt-get update && apt-get -y install git procps lsb-release

# Clean up
RUN apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

#ENV GOROOT /go
ADD $TARGETARCH $GOROOT
ADD $TARGETARCH/bin $GOPATH/bin
ADD $TARGETARCH/pkg $GOPATH/pkg
# Set the default shell to bash instead of sh
