name: Faketime-Go

on:
  push:
    branches: [ release/* ]
  pull_request:
    branches: [ release/* ]

jobs:
  build:
    name: Build
#    runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
        os: [ ubuntu-20.04 ]
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: build by all.bash
        run: |
          export GOROOT_BOOTSTRAP=`pwd`
          export CGO_ENABLE=0
          uname -a
          go env
          ls 
          pwd
          export GOARCH=${{matrix.arch}}
          env
          cd src && ./all.bash && cd -
          ls -al
      - name: Build the Docker image
        run: |
#          docker build . --file Dockerfile --tag asppj/go-builder:18.5faketime
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker buildx build --platform linux/${{matrix.arch}} -t asppj/go-builder:18.6faketime  --file Dockerfile .
          docker push asppj/go-builder:18.6faketime
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASS}}

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |
      #       Changes in this Release
      #       - SetDemFakeTime
      #     draft: false
      #     prerelease: false



